import { StyleSheet } from "react-native";
import colors from "../theme";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: -27,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceDivider,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.primary,
  },
  headerButtons: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  statButton: {
    backgroundColor: colors.background,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderColor: colors.surfaceDivider,
    borderWidth: 1,
  },
  statButtonText: {
    color: colors.headerBackground,
    fontWeight: "600",
    fontSize: 14,
  },
  addButton: {
    backgroundColor: colors.background,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderColor: colors.surfaceDivider,
    borderWidth: 1,
  },
  addButtonText: {
    color: colors.headerBackground,
    fontWeight: "600",
    fontSize: 14,
  },
  loader: {
    marginTop: 50,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyText: {
    fontSize: 16,
    color: colors.textMuted,
  },
  listContent: {
    padding: 12,
  },
  alarmItem: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  alarmHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  alarmTime: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
  },
  alarmType: {
    fontSize: 12,
    backgroundColor: colors.headerBackground,
    color: "white",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
  },
  alarmLocation: {
    fontSize: 13,
    color: colors.text,
    marginBottom: 4,
  },
  alarmDescription: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 4,
  },
  actions: {
    padding: 12,
    gap: 8,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceDivider,
  },
  backBtn: {
    flex: 1,
    backgroundColor: colors.headerBackground,
    padding: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 50,
  },
  backBtnText: {
    color: colors.text,
    fontWeight: "600",
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    justifyContent: "space-between",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: colors.headerBackground,
    borderBottomWidth: 1,
    borderBottomColor: colors.textMuted,
  },
  modalCloseButton: {
    fontSize: 24,
    color: "white",
    fontWeight: "bold",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "white",
  },
  modalContent: {
    flex: 1,
    backgroundColor: colors.surface,
    padding: 20,
    paddingBottom: 0,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textMuted,
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    backgroundColor: colors.background,
    color: colors.text,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceDivider,
    marginBottom: 12,
  },
  detailLabel: {
    fontWeight: "600",
    color: colors.textMuted,
  },
  detailValue: {
    color: colors.text,
  },
  modalActions: {
    flexDirection: "row",
    gap: 5,
    padding: 20,
    paddingTop: 10,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceDivider,
  },
  saveBtn: {
    flex: 1,
    backgroundColor: colors.headerBackground,
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  saveBtnText: {
    color: "white",
    fontWeight: "600",
  },
  cancelBtn: {
    flex: 1,
    backgroundColor: colors.surfaceBorder,
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelBtnText: {
    color: colors.text,
    fontWeight: "600",
  },
  deleteBtn: {
    flex: 1,
    backgroundColor: colors.danger,
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  deleteBtnText: {
    color: "white",
    fontWeight: "600",
  },
  crewSection: {
    marginTop: 20,
    padding: 12,
    backgroundColor: colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  crewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  crewTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  addCrewBtn: {
    padding: 6,
    backgroundColor: colors.headerBackground,
    borderRadius: 6,
  },
  addCrewText: {
    fontSize: 16,
    color: "white",
  },
  noCrewText: {
    fontSize: 14,
    color: colors.textMuted,
    fontStyle: "italic",
  },
  crewItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    marginBottom: 8,
    backgroundColor: colors.background,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: colors.headerBackground,
  },
  crewItemContent: {
    flex: 1,
  },
  crewPosition: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: "500",
  },
  crewName: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    marginTop: 4,
  },
  crewRemove: {
    fontSize: 18,
    color: colors.danger,
    paddingHorizontal: 8,
  },
  positionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  positionBtn: {
    flex: 1,
    minWidth: "45%",
    paddingVertical: 12,
    paddingHorizontal: 10,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
    borderRadius: 8,
    alignItems: "center",
  },
  positionBtnActive: {
    backgroundColor: colors.headerBackground,
    borderColor: colors.headerBackground,
  },
  positionBtnAssigned: {
    opacity: 0.5,
  },
  positionBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.text,
  },
  positionBtnTextActive: {
    color: "white",
  },
});
export default styles;